### ISSUE TITLE
Question about position

### ISSUE THREAD

**Issue by anneso-duchene** [ayalma/ExpandableRecyclerView#4]
First, thanks for this library !
I have a quick question. Can you tell me if a way exist to find the group and the child position based on the position you get via adapter.getPosition() ?

For example if the adapter.getPosition() return 3, the group position is 0 et the child position is 1.

Thanks in advance : )

**Comment by ayalma** [comment]
Sorry my friend. I'm in military service . And I'm away from coding .
Btw you can get the idea from this code

  @Override

        public void onBindViewHolder(ViewHolder holder, int i)

        {

            int group = 0;

            while (group <= getGroupItemCount())

            {

                if (i > 0 && !isExpanded(group))

                {

                    i--;

                    group++;

                    continue;

                }

                if (i > 0 && isExpanded(group))

                {

                    i--;

                    if (i < getChildItemCount(group)) {

                        onBindChildViewHolder((CVH) holder, group, i);

                        return;

                    }

                    i -= getChildItemCount(group);

                    group++;

                    continue;

                }

                if (i == 0) {

                    onBindGroupViewHolder((GVH) holder, group);

                    return;

                }

            }

            throw new IndexOutOfBoundsException();

        }

**Comment by anneso-duchene** [comment]
Thanks : )
