### ISSUE TITLE
ERROR: Failed to resolve: com.github.ayalma:ExpandableRecyclerView:0.2.0

### ISSUE THREAD

**Issue by rahulkushwaha482** [ayalma/ExpandableRecyclerView#8]
ERROR: Failed to resolve: com.github.ayalma:ExpandableRecyclerView:0.2.0 .Please check this .This happens in the classpath 3.4.1

**Comment by ayalma** [comment]
Hi sorry for delay 
Use this
```  implementation 'com.github.ayalma:ExpandableRecyclerView:0.4.0' ```

**Comment by rahulkushwaha-dev** [comment]
Thnaks.. @ayalma

**Comment by SananHaji** [comment]
Failed to resolve: com.github.ayalma:ExpandableRecyclerView:0.4.0
this error happens(
